### PR TITLE
removed obsolete master_account reference

### PR DESCRIPTION
**Pull request by AngelBlock**

### CODE REVIEW

**Comment by telezhnaya** [comment]
I suggest not to add here Dockerfile since we have it in `near-sdk-rs`
I fixed the container there and minimized number of required libraries: https://github.com/near/near-sdk-rs/pull/454
Just checked, it also works fine with lockup-factory.

**Comment by AngelBlock** [comment]
> I suggest not to add here Dockerfile since we have it in `near-sdk-rs`
> I fixed the container there and minimized number of required libraries: [near/near-sdk-rs#454](https://github.com/near/near-sdk-rs/pull/454)
> Just checked, it also works fine with lockup-factory.

The docker container is not part of this PR, just a factory code.

**Comment by telezhnaya** [comment]
> > I suggest not to add here Dockerfile since we have it in `near-sdk-rs`
> > I fixed the container there and minimized number of required libraries: [near/near-sdk-rs#454](https://github.com/near/near-sdk-rs/pull/454)
> > Just checked, it also works fine with lockup-factory.
> 
> The docker container is not part of this PR, just a factory code.

It is. You added the configuration by the last commit

**Comment by AngelBlock** [comment]
> > > I suggest not to add here Dockerfile since we have it in `near-sdk-rs`
> > > I fixed the container there and minimized number of required libraries: [near/near-sdk-rs#454](https://github.com/near/near-sdk-rs/pull/454)
> > > Just checked, it also works fine with lockup-factory.
> > 
> > 
> > The docker container is not part of this PR, just a factory code.
> 
> It is. You added the configuration by the last commit

Ops, sorry, it was added automatically, keep forgetting of this `bug`=`feature`, I'll remove the PR and resubmit. Apologies.

**Comment by AngelBlock** [comment]
Closing to avoid adding docker container to the lockup repo.

**Pull request closed without merging**
