### PR TITLE
lockup [3.0.0]: Update lockup release duration

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
### `3.0.0`

- Release duration now starts from the moment the tokens are unlocked. 
The tokens are unlocked at the following timestamp `max(transfers_enabled_timestamp + lockup_duration, lockup_timestamp)`.
NOTE: If the `lockup_timestamp` is not specified, the tokens are unlocked at `transfers_enabled_timestamp + lockup_duration`.

The contracts were rebuilt using contract builder from `near-sdk-rs`

## Test plan

- Updated unittests and sim tests to match the new behavior

### CODE REVIEW

**Review by bowenwang1996 — APPROVED** [review]

**Review by willemneal — APPROVED** [review]

**Comment by ilblackdragon** [comment]
Merge?

**Review by frol — APPROVED** [review]
I bumped into the same issue, and confirm the fix is correct

**Comment by frol** [comment]
FYI, contract-lookup has been also updated: https://github.com/near/account-lookup/pull/4

**Comment by marcinbodnar** [comment]
> FYI, contract-lookup has been also updated: [near/account-lookup#4](https://github.com/near/account-lookup/pull/4)

Thanks @frol

**Pull request merged**
