### PR TITLE
[Lockup]: Upgrade to near-sdk version 3.1.0

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
- Updating `near-sdk` version to `3.1.0`
- Reimplementing simulation tests using `near-sdk-sim`
- Removing `rust-toolchain` as well toolchain from `build.sh`, because contract-builder from `near-sdk-rs` uses fixed Rust version, instead of the toolchain.
- Recompiling lockup with contract builder from `near-sdk-rs` using Docker.

## Test plan:
- Unit tests + simulation tests

### CODE REVIEW

**Review by telezhnaya — DISMISSED** [review]
Sorry, but it does not work still.

On Mac, `cargo test` gives
```
Finished test [unoptimized + debuginfo] target(s) in 3m 11s
     Running unittests (target/debug/deps/lockup_contract-6337a50a2613867b)

running 30 tests
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/telezhnaya/dev/core-contracts/lockup/target/debug/deps/lockup_contract-6337a50a2613867b` (signal: 11, SIGSEGV: invalid memory reference)
```

In the [Linux container](https://github.com/near/near-sdk-rs/blob/master/contact-builder/Dockerfile), I had to additionaly install llvm and clang, and even with it I have
```
error: failed to run custom build command for `jemalloc-sys v0.3.2`

Caused by:
  process didn't exit successfully: `/core-contracts/lockup/target/debug/build/jemalloc-sys-1687736efd9cc22f/build-script-build` (exit code: 101)
  --- stdout
  TARGET=x86_64-unknown-linux-gnu
  HOST=x86_64-unknown-linux-gnu
  NUM_JOBS=8
  OUT_DIR="/core-contracts/lockup/target/debug/build/jemalloc-sys-b9256c5ce59e6669/out"
  BUILD_DIR="/core-contracts/lockup/target/debug/build/jemalloc-sys-b9256c5ce59e6669/out/build"
  SRC_DIR="/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.2"
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC="cc"
  CFLAGS="-O0 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall"
  JEMALLOC_REPO_DIR="jemalloc"
  JEMALLOC_SRC_DIR="/core-contracts/lockup/target/debug/build/jemalloc-sys-b9256c5ce59e6669/out/jemalloc"
  cargo:rustc-cfg=prefixed
  --with-jemalloc-prefix=_rjem_
  running: "sh" "/core-contracts/lockup/target/debug/build/jemalloc-sys-b9256c5ce59e6669/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/core-contracts/lockup/target/debug/build/jemalloc-sys-b9256c5ce59e6669/out"
```

**Comment by telezhnaya** [comment]
Also added `libjemalloc-dev` to Dockerfile, got new error

```
   Compiling near-primitives v0.1.0-pre.1
error: could not compile `cranelift-codegen`

Caused by:
  process didn't exit successfully: `rustc --crate-name cranelift_codegen --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.67.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="enable-serde"' --cfg 'feature="gimli"' --cfg 'feature="serde"' --cfg 'feature="std"' --cfg 'feature="unwind"' -C metadata=e4b8fa2bfba3a5c8 -C extra-filename=-e4b8fa2bfba3a5c8 --out-dir /core-contracts/lockup/target/debug/deps -L dependency=/core-contracts/lockup/target/debug/deps --extern byteorder=/core-contracts/lockup/target/debug/deps/libbyteorder-ac5a4c6ef5e6f997.rmeta --extern cranelift_bforest=/core-contracts/lockup/target/debug/deps/libcranelift_bforest-0095e3316b43a6e0.rmeta --extern cranelift_codegen_shared=/core-contracts/lockup/target/debug/deps/libcranelift_codegen_shared-d8298367ab96194d.rmeta --extern cranelift_entity=/core-contracts/lockup/target/debug/deps/libcranelift_entity-e508455d8e1a7a54.rmeta --extern gimli=/core-contracts/lockup/target/debug/deps/libgimli-df91d56a343182c3.rmeta --extern log=/core-contracts/lockup/target/debug/deps/liblog-a06190083d62aff1.rmeta --extern regalloc=/core-contracts/lockup/target/debug/deps/libregalloc-f60378d91b9907fb.rmeta --extern serde=/core-contracts/lockup/target/debug/deps/libserde-b26298ab3d9ebfdb.rmeta --extern smallvec=/core-contracts/lockup/target/debug/deps/libsmallvec-22a3f1cd252b8e37.rmeta --extern target_lexicon=/core-contracts/lockup/target/debug/deps/libtarget_lexicon-4bdab61c5128c636.rmeta --extern thiserror=/core-contracts/lockup/target/debug/deps/libthiserror-42bb7953d51fe18d.rmeta --cap-lints allow --cfg 'feature="x86"'` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: c++: fatal error: Killed signal terminated program cc1plus
warning: compilation terminated.
warning: c++: fatal error: Killed signal terminated program cc1plus
warning: compilation terminated.

error: build failed
```

**Comment by telezhnaya** [comment]
It's more important to provide the solution with a suitable container, but the error from Mac looks suspicious. Looks like we are trying to access the memory that does not belong to us or something like that. It could point to a severe problem.

**Review by telezhnaya — APPROVED** [review]
I haven't checked `lockup/tests/spec.rs` since it's the enormous number of changes and I just trust @evgenykuzyakov 
`cargo test` runs perfectly, so I suggest merging it, it's an improvement for sure.

**Comment by telezhnaya** [comment]
@bowenwang1996 please have a look

**Review by bowenwang1996 — APPROVED** [review]

**Pull request merged**
